
services:
  db:
    image: postgres:16
    container_name: simplepolls-postgresdb
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - simplepolls_pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  simplepolls_pgdata: